name: "TF Apply on merge"
on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  merge:
    if: github.event.pull_request.merged == true
    name: "do the thing"
    runs-on: ubuntu-latest
    steps:
      - name: "set-env"
        run: echo " ${{ github.head_ref }} "
      - name: "determine tf folder"
        run: |
          tf_branch=$(echo "${{ github.head_ref }}" | cut -d "/" -f 1)
          echo $tf_branch
          if [[ $tf_branch = "staging" ]]
          then
            echo "GH_HEAD_BRANCH=stage" >> $GITHUB_ENV
          elif [[ $tf_branch = "production" ]]
          then
            echo "GH_HEAD_BRANCH=prod" >> $GITHUB_ENV
          else 
            echo "GH_HEAD_BRANCH=default" >> $GITHUB_ENV
          fi
      - name: "echo workspace"
        run: echo $GH_HEAD_BRANCH
